version: '3'

services:
  web_server:
    # image: php:apache # on utiliplus une Image on va construire a partir du Dockerfile pour activer php avec Apache
    build: ./backend/
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80 # conaiter:machine

  db:
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=MonRootyPass
      - MYSQL_DATABASE=camagru_db
      - MYSQL_USER=serviceMan
      - MYSQL_PASSWORD=psw

  db_manager:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db #Set le container db as Host
    depends_on:
      - db
  # front:

volumes:
  db: # creer un volume named db
