version: '3.8'

services:
  web_server:
    # image: php:apache # on utiliplus une Image on va construire a partir du Dockerfile pour activer php avec Apache
    build: ./backend/
    restart: unless-stopped
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80
    networks:
      - camagru_back_network
    depends_on:
      - db
      - db_manager

  db:
    image: mysql:8.1.0
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=MonRootyPass
      - MYSQL_DATABASE=camagru_db
      - MYSQL_USER=serviceMan
      - MYSQL_PASSWORD=psw
    networks:
      - camagru_back_network


  db_manager:
    image: phpmyadmin:5.2.1
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db #Set le container 'db' as Host
    networks:
      - camagru_back_network
    depends_on:
      - db

  front:
    build: ./frontend/
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - web_server
    volumes:
    # Volume pour le DEV permetant rebuild en temps reel
      - ./frontend/front-react:/app
    # Assure l'utilisation des modules installes dans le container
      - /app/node_modules


networks:
  camagru_back_network:
    driver: bridge

volumes:
  db: # creer un volume named db
