version: '3'

services:
  web_server:
    # image: php:apache # on utiliplus une Image on va construire a partir du Dockerfile pour activer php avec Apache
    build: ./backend/
    volumes:
      - ./:/var/www/html/
    ports:
      - 80:80 # conaiter:machine
    depends_on:
      - db
      - db_manager

  db:
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=MonRootyPass
      - MYSQL_DATABASE=camagru_db
      - MYSQL_USER=serviceMan
      - MYSQL_PASSWORD=psw

  db_manager:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db #Set le container 'db' as Host
    depends_on:
      - db
  # front:
  #   build: ./frontend
  #   volumes:
  #     - ./frontend:/app
  #     - /app/nodes_modules
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - web_server




volumes:
  db: # creer un volume named db
